// This file is generated by kconfig_compiler from contactdesktopcouchresource.kcfg.
// All changes you do to this file will be lost.
#ifndef SETTINGS_H
#define SETTINGS_H

#include <kconfigskeleton.h>
#include <kdebug.h>

class Settings : public KConfigSkeleton
{
  public:

    static Settings *self();
    ~Settings();

    /**
      Set Do not change the actual backend data.
    */
    static
    void setReadOnly( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "ReadOnly" ) ))
        self()->mReadOnly = v;
    }

    /**
      Get Do not change the actual backend data.
    */
    static
    bool readOnly()
    {
      return self()->mReadOnly;
    }

    /**
      Get Item object corresponding to ReadOnly()
    */
    ItemBool *readOnlyItem()
    {
      return mReadOnlyItem;
    }

  protected:
    Settings();
    friend class SettingsHelper;


    // General
    bool mReadOnly;

  private:
    ItemBool *mReadOnlyItem;
};

#endif

