/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -a settingsadaptor -i settings.h -l Settings /media/storage/PROGRAMMING/MasterThesis/GitRepo/DesktopCouchResource/calendardesktopcouch/calendardesktopcouch/qtcreator-build/org.kde.Akonadi.calendardesktopcouch.Settings.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SETTINGSADAPTOR_H_1284058377
#define SETTINGSADAPTOR_H_1284058377

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "settings.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.Akonadi.calendardesktopcouch.Settings
 */
class SettingsAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.Akonadi.calendardesktopcouch.Settings")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.Akonadi.calendardesktopcouch.Settings\">\n"
"    <method name=\"readOnly\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"setReadOnly\">\n"
"      <arg direction=\"in\" identifier=\"value\" type=\"b\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    SettingsAdaptor(Settings *parent);
    virtual ~SettingsAdaptor();

    inline Settings *parent() const
    { return static_cast<Settings *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool readOnly();
    void setReadOnly(bool in0);
Q_SIGNALS: // SIGNALS
};

#endif
