#!/bin/bash
# Author: Wojciech Mąka
# 
#
#
progress ()
{
  echo $1 | dialog --title  "Installing prerequisites..."    \
                   --backtitle "Installing prerequisites..." \ 
                   --gauge "Installation in progress... " 10 40 $1
}
installation () {
    if [ $1 -eq 0 ]
    then
      if [ ! -e "/usr/bin/git" ]
      then
        sudo apt-get install git-core 
        progress 2
      fi
    fi
    if [ $1 -eq 1 ]
    then
      sudo apt-get install kdepimlibs5      
      progres 3 
      sudo apt-get install kdepimlibs5-dev  
      progres 4
      sudo apt-get install kdepimlibs-data 
      progres 5
      sudo apt-get install kdepim           
      progres 6
      sudo apt-get install kdepim-dev       
      progres 7
      sudo apt-get install libkdepim4       
      progres 8
    fi
    if [ $1 -eq 2 ]
    then
      REPLY="y"
      if [ -e "/usr/lib/libqjson.so" ]
      then
         dialog --title "Reinstallation" \
                --backtitle "Reinstallation" \
                --yesno "Do You want to reinstall library ?" 5 30
      fi        
      if [ $REPLY = "y" ]
      then
	if [ ! -e "QJSON_SOURCES" ]
	then
	  mkdir QJSON_SOURCES
	fi
	cd QJSON_SOURCES
	git clone -v git://gitorious.org/qjson/qjson.git 
	  cd qjson
	  mkdir build
	  cd build
	  cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RELEASE ../
	  make
	  sudo make install
	  cd ..
      fi
      prog=50
      return $prog
    fi
    if [ $1 -eq 3 ]
    then 
      REPLY="y"
      if [ -e "/usr/lib/libqoauth.so" ]
      then

	REPLY=$ret
      fi        
      if [ $REPLY = "y" ]
      then
	if [ ! -e "QOAUTH_SOURCES" ]
	then 
	  mkdir QOAUTH_SOURCES
	fi
	cd QOAUTH_SOURCES 
	git clone -v git://github.com/ayoy/qoauth.git
	  cd qoauth
	  qmake 
	  make  
	  sudo make install	
      fi
      prog=100 
      return $prog  
    fi   
}


sudo apt-get install dialog 
tmpv=${0%/*}
echo $tmpv
cd $tmpv

dialog --title "Installing prerequisites..." \
--backtitle "Installing prerequisites..." \
--msgbox "This installer will install all dependecies needed for buildig: couchdb-qt, " 10 40


installation 0
installation 1
installation 2
installation 0

